In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

In [2]:
def sigmoid(x):
  return 1.0/(1 + np.exp(-x))

In [3]:
def predict(w, X):
  return sigmoid(X@w)

In [4]:
def loss(w, X, y):
  z = predict(w, X)
  return -np.mean(y*np.log(z) + (1-y)*np.log(1-z)) 

In [5]:
numOfIteration = 1000
learning_rate=0.01
def Normal_Equation(X,y):
  W=np.ones(row)
  W = np.linalg.inv(X.T@X)@X.T@y
  return W
Normal_Equation(X,y)

NameError: ignored

In [ ]:
numOfIteration = 1000
cost = np.zeros((numOfIteration,1))
learning_rate = 0.01
W=np.ones(row)
for i in range(1, numOfIteration):
# Tính giá trị dự đoán
  y_predict = sigmoid(predict(W,X))
  # cost[i] = -np.sum(np.multiply(y, np.log(y_predict)) + \np.multiply(1-y, np.log(1-y_predict)))
# Gradient descent

w = w - learning_rate * np.dot(x.T, y_predict-y)
W
# print(cost[i])


In [ ]:
ar=np.array([1,1,1,1,1,1,1])
ar.shape

(7,)

In [8]:
from google.colab import drive
drive.mount('/content/gdrive')

data = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/TTNT_2022/heart.csv')
data.head()

Mounted at /content/gdrive


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [7]:
from google.colab import files
uploaded = files.upload()

data = pd.read_csv('heart.csv')
data.head()



df

FileNotFoundError: ignored

In [17]:
y = data["target"]
X = data.drop('target',axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state = 0)

W_init=np.ones(y.size,dtype=int)

In [ ]:
data=df.to_numpy()
colums=np.size(data,1)
row=np.size(data,0)

y=np.array(data[:,colums-1])
X=np.array(data[:,:])
X[:,colums-1]=1
W_init=np.ones((1,colums))


In [ ]:
print(X)
print(y)
print(W_init)

[[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  1.]
 [57.  1.  0. ...  1.  3.  1.]
 [57.  0.  1. ...  1.  2.  1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0

In [ ]:
W_init=np.ones((colums,1))
lost_hist=np.ones((2000,colums))
W,lost_hist=logistic_regression(W_init, X, y)